### ISSUE TITLE
runner_provides

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/runner#17]
This is a part of my master plan to make `runner` not just a task runner, but a good build system for building small-to-medium projects using tools, that accept multiple inputs and produce multiple outputs.

Directive `runner_provides` declares files that will be produced within a context of a task.

It assumes that  `runner_depends` can accept file names.

**Example:**

``` bash
task_npm() {
  runner_depends package.json
  runner_provides node_modules
  ## if package.json is newer than node_modules, run `npm install`.
  npm install --no-progress
  touch node_modules
}

task_webpack() {
  runner_depends task_npm
  runner_provides public/{user,admin,common}.bundle.js
  ## If `task_npm` (and files it provides) are newer than bundles,
  ## run `webpack`.
  webpack
}
```

**TODO:**
- [ ] Directive: `runner_depends` #16
- [ ] Add a dummy `runner_provides` function.
- [ ] Skip task if files in `runner_provides` are newer than dependencies in `runner_depends`.
- [ ] Perform deeper dependency checks.

**Comment by stylemistake** [comment]
Spec is too rough, closing for now.
